import 'package:flutter/material.dart';
import '../services/auth_service.dart';
import '../services/firebase_service.dart';
import '../models/message_model.dart';
import '../models/user_model.dart';
import '../theme/app_theme.dart';
import 'package:timeago/timeago.dart' as timeago;

import 'package:file_picker/file_picker.dart';
import 'package:url_launcher/url_launcher.dart';
import 'dart:io';
import 'profile_page.dart';
import 'group_info_screen.dart';

class ChatScreen extends StatefulWidget {
  final String chatId;
  final UserModel? otherUser;
  final String? chatName;
  final String? chatImage;
  final bool isGroup;

  const ChatScreen({
    super.key, 
    required this.chatId, 
    this.otherUser,
    this.chatName,
    this.chatImage,
    this.isGroup = false,
  });

  @override
  State<ChatScreen> createState() => _ChatScreenState();
}

class _ChatScreenState extends State<ChatScreen> {
  final TextEditingController _messageController = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  File? _selectedFile;
  String? _attachmentType; // 'image', 'pdf', 'other'
  bool _isUploading = false;

  @override
  void initState() {
    super.initState();
    // Mark chat as read when opening
    final currentUser = AuthService().currentUser;
    if (currentUser != null) {
      FirebaseService().markChatAsRead(widget.chatId, currentUser.uid);
    }
  }

  Future<void> _pickFile() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'],
    );

    if (result != null) {
      String? path = result.files.single.path;
      if (path != null) {
        setState(() {
          _selectedFile = File(path);
          String ext = result.files.single.extension?.toLowerCase() ?? '';
          if (['jpg', 'jpeg', 'png'].contains(ext)) {
            _attachmentType = 'image';
          } else if (ext == 'pdf') {
            _attachmentType = 'pdf';
          } else {
            _attachmentType = 'other';
          }
        });
      }
    }
  }

  void _removeAttachment() {
    setState(() {
      _selectedFile = null;
      _attachmentType = null;
    });
  }

  void _sendMessage() async {
    final content = _messageController.text.trim();
    if (content.isEmpty && _selectedFile == null) return;

    final currentUser = AuthService().currentUser;
    if (currentUser == null) return;

    setState(() => _isUploading = true);

    String? attachmentUrl;
    String? type = _attachmentType;

    try {
      if (_selectedFile != null) {
        attachmentUrl = await FirebaseService().uploadChatAttachment(_selectedFile!, widget.chatId);
      }

      final message = MessageModel(
        id: '', // Generated by Firestore
        senderId: currentUser.uid,
        content: content,
        timestamp: DateTime.now(),
        isRead: false,
        attachmentUrl: attachmentUrl,
        attachmentType: type,
      );

      // Get participants to notify
      List<String> otherUserIds = [];
      if (widget.isGroup) {
        // Fetch chat details to get current participants
        // This is a bit inefficient to do on every send, but ensures correctness
        // Ideally we should have the chat model available in the state
        final chatStream = FirebaseService().getChatStream(widget.chatId);
        final chat = await chatStream.first;
        otherUserIds = chat.participants.where((id) => id != currentUser.uid).toList();
      } else {
        if (widget.otherUser != null) {
          otherUserIds = [widget.otherUser!.id];
        }
      }

      await FirebaseService().sendMessage(widget.chatId, message, otherUserIds);
      
      _messageController.clear();
      _removeAttachment();

      // Scroll to bottom
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          0, // List is reversed
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text("Failed to send message")),
      );
    } finally {
      if (mounted) setState(() => _isUploading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final currentUser = AuthService().currentUser;

    return Scaffold(
      backgroundColor: AppTheme.background,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, color: AppTheme.secondary),
          onPressed: () => Navigator.pop(context),
        ),
        title: GestureDetector(
          onTap: () {
            if (widget.isGroup) {
              Navigator.push(context, MaterialPageRoute(builder: (context) => GroupInfoScreen(chatId: widget.chatId)));
            } else if (widget.otherUser != null) {
              Navigator.push(context, MaterialPageRoute(builder: (context) => ProfilePage(userId: widget.otherUser!.id)));
            }
          },
          child: Row(
            children: [
              CircleAvatar(
                radius: 16,
                backgroundImage: widget.isGroup 
                  ? (widget.chatImage != null ? NetworkImage(widget.chatImage!) : null)
                  : NetworkImage(widget.otherUser!.photoUrl),
                child: (widget.isGroup && widget.chatImage == null) 
                  ? const Icon(Icons.group, size: 16, color: Colors.grey) 
                  : null,
              ),
              const SizedBox(width: 10),
              Text(
                widget.isGroup ? (widget.chatName ?? "Group") : widget.otherUser!.name,
                style: const TextStyle(color: AppTheme.secondary, fontWeight: FontWeight.bold, fontSize: 16),
              ),
            ],
          ),
        ),
      ),
      body: Column(
        children: [
          Expanded(
            child: StreamBuilder<List<MessageModel>>(
              stream: FirebaseService().getMessages(widget.chatId),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(child: CircularProgressIndicator());
                }

                if (!snapshot.hasData || snapshot.data!.isEmpty) {
                  return Center(
                    child: Text(
                      widget.isGroup ? "Start the conversation!" : "Say hello to ${widget.otherUser?.name ?? 'User'}!", 
                      style: TextStyle(color: Colors.grey[500])
                    ),
                  );
                }

                final messages = snapshot.data!;

                return ListView.builder(
                  controller: _scrollController,
                  reverse: true, // Show newest at bottom
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                  itemCount: messages.length,
                  itemBuilder: (context, index) {
                    final message = messages[index];
                    final isMe = message.senderId == currentUser?.uid;

                    return Align(
                      alignment: isMe ? Alignment.centerRight : Alignment.centerLeft,
                      child: Container(
                        margin: const EdgeInsets.only(bottom: 8),
                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                        constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width * 0.75),
                        decoration: BoxDecoration(
                          color: isMe ? AppTheme.primary : Colors.white,
                          borderRadius: BorderRadius.only(
                            topLeft: const Radius.circular(16),
                            topRight: const Radius.circular(16),
                            bottomLeft: isMe ? const Radius.circular(16) : const Radius.circular(4),
                            bottomRight: isMe ? const Radius.circular(4) : const Radius.circular(16),
                          ),
                          boxShadow: [
                            if (!isMe)
                              BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 4, offset: const Offset(0, 2)),
                          ],
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            if (message.attachmentUrl != null) ...[
                              if (message.attachmentType == 'image')
                                GestureDetector(
                                  onTap: () {
                                    // TODO: Open full screen image
                                  },
                                  child: ClipRRect(
                                    borderRadius: BorderRadius.circular(8),
                                    child: Image.network(
                                      message.attachmentUrl!,
                                      height: 150,
                                      width: 200,
                                      fit: BoxFit.cover,
                                      loadingBuilder: (context, child, loadingProgress) {
                                        if (loadingProgress == null) return child;
                                        return Container(
                                          height: 150,
                                          width: 200,
                                          color: Colors.black12,
                                          child: const Center(child: CircularProgressIndicator()),
                                        );
                                      },
                                    ),
                                  ),
                                )
                              else
                                GestureDetector(
                                  onTap: () async {
                                    final Uri url = Uri.parse(message.attachmentUrl!);
                                    if (!await launchUrl(url, mode: LaunchMode.externalApplication)) {
                                      if (context.mounted) {
                                        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Could not open file")));
                                      }
                                    }
                                  },
                                  child: Container(
                                    padding: const EdgeInsets.all(8),
                                    decoration: BoxDecoration(
                                      color: Colors.black.withOpacity(0.1),
                                      borderRadius: BorderRadius.circular(8),
                                    ),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      children: [
                                        Icon(
                                          message.attachmentType == 'pdf' ? Icons.picture_as_pdf : Icons.insert_drive_file,
                                          color: isMe ? Colors.white : AppTheme.secondary,
                                        ),
                                        const SizedBox(width: 8),
                                        Text(
                                          "Attachment",
                                          style: TextStyle(
                                            color: isMe ? Colors.white : AppTheme.secondary,
                                            decoration: TextDecoration.underline,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              const SizedBox(height: 8),
                            ],
                            if (message.content.isNotEmpty)
                              Text(
                                message.content,
                                style: TextStyle(
                                  color: isMe ? Colors.white : AppTheme.secondary,
                                  fontSize: 15,
                                ),
                              ),
                            const SizedBox(height: 4),
                            Text(
                              timeago.format(message.timestamp, locale: 'en_short'),
                              style: TextStyle(
                                color: isMe ? Colors.white.withOpacity(0.7) : Colors.grey[500],
                                fontSize: 10,
                              ),
                            ),
                          ],
                        ),
                      ),
                    );
                  },
                );
              },
            ),
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            decoration: BoxDecoration(
              color: Colors.white,
              boxShadow: [
                BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 10, offset: const Offset(0, -5)),
              ],
            ),
            child: SafeArea(
              child: Column(
                children: [
                  if (_selectedFile != null)
                    Container(
                      margin: const EdgeInsets.only(bottom: 8),
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(
                        color: Colors.grey[100],
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: AppTheme.primary.withOpacity(0.3)),
                      ),
                      child: Row(
                        children: [
                          if (_attachmentType == 'image')
                            ClipRRect(
                              borderRadius: BorderRadius.circular(8),
                              child: Image.file(_selectedFile!, width: 50, height: 50, fit: BoxFit.cover),
                            )
                          else
                            Icon(
                              _attachmentType == 'pdf' ? Icons.picture_as_pdf : Icons.insert_drive_file,
                              size: 40,
                              color: AppTheme.secondary,
                            ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Text(
                              _selectedFile!.path.split('/').last,
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                              style: const TextStyle(fontWeight: FontWeight.bold),
                            ),
                          ),
                          IconButton(
                            icon: const Icon(Icons.close, color: Colors.red),
                            onPressed: _removeAttachment,
                          ),
                        ],
                      ),
                    ),
                  Row(
                    children: [
                      IconButton(
                        icon: const Icon(Icons.attach_file_rounded, color: AppTheme.secondary),
                        onPressed: _pickFile,
                      ),
                      Expanded(
                        child: Container(
                          padding: const EdgeInsets.symmetric(horizontal: 16),
                          decoration: BoxDecoration(
                            color: Colors.grey[100],
                            borderRadius: BorderRadius.circular(24),
                          ),
                          child: TextField(
                            controller: _messageController,
                            decoration: const InputDecoration(
                              hintText: "Type a message...",
                              border: InputBorder.none,
                              isDense: true,
                              contentPadding: EdgeInsets.symmetric(vertical: 12),
                            ),
                            textCapitalization: TextCapitalization.sentences,
                            minLines: 1,
                            maxLines: 4,
                          ),
                        ),
                      ),
                      const SizedBox(width: 8),
                      GestureDetector(
                        onTap: _isUploading ? null : _sendMessage,
                        child: Container(
                          padding: const EdgeInsets.all(10),
                          decoration: BoxDecoration(
                            color: _isUploading ? Colors.grey : AppTheme.primary,
                            shape: BoxShape.circle,
                          ),
                          child: _isUploading 
                            ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                            : const Icon(Icons.send_rounded, color: Colors.white, size: 20),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
