import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../theme/app_theme.dart';
import '../models/post_model.dart';
import '../services/firebase_service.dart';
import '../services/auth_service.dart';

import '../widgets/loading_widget.dart';

class CreatePostScreen extends StatefulWidget {
  const CreatePostScreen({super.key});

  @override
  State<CreatePostScreen> createState() => _CreatePostScreenState();
}

class _CreatePostScreenState extends State<CreatePostScreen> {
  final _contentController = TextEditingController();
  final FirebaseService _firebaseService = FirebaseService();
  final AuthService _authService = AuthService();
  
  String _selectedType = 'Question'; // Question or Achievement
  bool _isLoading = false;

  Future<void> _createPost() async {
    if (_contentController.text.trim().isEmpty) return;

    setState(() => _isLoading = true);

    try {
      final user = _authService.currentUser;
      if (user == null) throw "User not logged in";

      // Fetch latest user data from Firestore
      final userModel = await _firebaseService.getUser(user.uid);

      // Create Post Model
      final post = PostModel(
        id: '', // Generated by Firestore
        authorId: user.uid,
        authorName: userModel?.name ?? user.displayName ?? 'Anonymous',
        authorPhotoUrl: userModel?.photoUrl.isNotEmpty == true ? userModel!.photoUrl : user.photoURL ?? '',
        school: userModel?.school ?? 'Unknown School',
        grade: userModel?.grade ?? '',
        content: _contentController.text.trim(),
        type: _selectedType,
        timestamp: DateTime.now(),
        likes: 0,
        comments: 0,
        isAchievement: _selectedType == 'Achievement',
      );

      await _firebaseService.createPost(post);

      if (mounted) {
        Navigator.pop(context); // Return to Feed
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error creating post: $e")),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.black),
        title: const Text("Create Post", style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: 16.0),
            child: TextButton(
              onPressed: _isLoading ? null : _createPost,
              style: TextButton.styleFrom(
                backgroundColor: AppTheme.primary,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
                padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 8),
              ),
              child: _isLoading 
                ? const LoadingWidget(size: 20, color: Colors.white)
                : const Text("Post", style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
            ),
          )
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            // User Info Row
            Row(
              children: [
                const CircleAvatar(
                  backgroundColor: AppTheme.secondary,
                  child: Icon(Icons.person, color: Colors.white),
                ),
                const SizedBox(width: 12),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(_authService.currentUser?.email?.split('@')[0] ?? "User", style: const TextStyle(fontWeight: FontWeight.bold)),
                    
                    // Type Selector
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          _selectedType = _selectedType == 'Question' ? 'Achievement' : 'Question';
                        });
                      },
                      child: Row(
                        children: [
                          Text(_selectedType, style: TextStyle(color: _selectedType == 'Question' ? AppTheme.primary : Colors.purple, fontSize: 12, fontWeight: FontWeight.bold)),
                          const Icon(Icons.arrow_drop_down, size: 16, color: Colors.grey),
                        ],
                      ),
                    ),
                  ],
                )
              ],
            ),
            
            const SizedBox(height: 24),

            // Content Input
            Expanded(
              child: TextField(
                controller: _contentController,
                maxLines: null,
                decoration: const InputDecoration(
                  hintText: "What's on your mind?",
                  border: InputBorder.none,
                  hintStyle: TextStyle(fontSize: 20, color: Colors.grey),
                ),
                style: const TextStyle(fontSize: 20),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
